--- 
# config file to run the AGN decomposition pipelines and functions
config: # Run AGNdecomp
  - run_type: FULL #Pipeline Type
    name: NAME #name of the IFS cube
    path: cubes/ #path to the data cubes
    verbose: False #Flag to activate verbosity
    ncpus: 10 #number of CPUs
    nameb: NAME.cube.fits.gz # base format naming of the IFS files
    test: True #flag to run the full analysis in test mode
    sampling: 1 #spectral sampling for the analysis in AA
    pipeline: False #run in pipeline mode
    clean: True #generate a full clean run
    psamp: 10 #spectral sampling of the previus phase, default 10 AA
    path_out: outputs/ #path of the output files
    head_dat: 0 #header data extension, default 0
    head_err: 1 #header error data extension, default 1
    mod_ind: 0 #model index for the run, default 0
    mod_ind0: 0 #model index for the initial run, default 0
    logp: True #use log scale for ploting the residual maps
    ext_name: externfunc #optional, name of the external module user defined function
    ext_path: '' #optional, path of the external module file user defined function
    ext_file: extern_file.py #optional, name of the externel module file user defined function
    wavew1: 4850.0 #optional, initial wavelength for the test analysis, default 4850 AA
    wavew2: 5150.0 #optional, final wavelength for the test analysis, default 5150 AA

configmap: # Run AGNdecomp for a 2D map
  - run_type: FULL #Pipeline Type
    name: NAME #name of the 2Dmap
    path: maps/ #path to the data map
    verbose: False #flag for verbosity
    ncpus: 10 #number of CPUs
    nameb: NAME.map.fits.gz #naming format base of the 2Dmap files
    path_out: outputs/ #path of the output files
    head_dat: 0 #header data extension, default 0
    head_err: 1 #header error data extension, default 1
    mod_ind: 0 #model index for the run, default 0
    mod_ind0: 0 #model index for the initial run, default 0
    logp: True #use log scale for ploting the residual maps
    ext_name: externfunc #name of the external module user defined function
    ext_path: '' #path of the external module file user defined function
    ext_file: extern_file.py #name of the externel module file user defined function

configmodel: # Run the rutine to obtain the cube models
  - run_type: FULL #Pipeline Type
    name: NAME #name of the IFS cube
    path: cubes/ #path to the data cubes
    nameb: NAME.cube.fits.gz #naming format base of the IFS files
    path_out: outputs/ #path of the output files
    pathc_out: outputs/ #path for the save data-cube
    head_dat: 0 #header data extension, default 0
    head_err: 1 #header error data extension, default 1
    ext_name: externfunc #optional, name of the external module user defined function
    ext_path: '' #optional, path of the external module file user defined function
    ext_file: extern_file.py #optional, name of the externel module file user defined function